### ISSUE TITLE
Problem in merged README instructions

### ISSUE THREAD

**Issue by covarell** [UniMiBAnalyses/D6EFTStudies#11]
I see some problems are now present in the README because some instructions specific to the 2e2mu VBS productions have been set as default. 

In particular, it is suggested to use a run card specific for 2e2mu and that is untested for other processes (the mjj > 100 GeV cut can cause problems for inclusive samples and semileptonic VBS for example). Less importantly, a manual copy of the create-folders for ZZ is suggested (in fact they should be just added and committed to this repository).

**Comment by covarell** [comment]
Also the instruction "ln -ns restricted*.dat ..." should be "ln -ns restrict*.dat ..."

**Comment by GiacomoBoldrini** [comment]
Updated the README.md, ZZ instruction are now listed in hiddden subsections. In place of a symbolic link we copy all the restriction cards in the UFO folder (creating duplicates but amount to 26MB). Now everything works
